name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-test-lint:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Check out the code
    - name: Checkout code
      uses: actions/checkout@v3

    # Step 2: Set up Python
    - name: Set up Python 3.9
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'

    # Step 3: Install dependencies
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    # Step 4: Run linting
    - name: Run flake8
      run: |
        pip install flake8
        flake8 .

    # Step 5: Run tests
    - name: Run tests
      run: |
        pip install pytest
        pytest

  dockerize:
    runs-on: ubuntu-latest
    needs: build-test-lint

    steps:
    # Step 1: Check out the code
    - name: Checkout code
      uses: actions/checkout@v3

    # Step 2: Build Docker image
    - name: Build Docker image
      run: |
        docker build -t Key-Logger-main .

    # Step 3: Push Docker image (Optional, if using Docker Hub)
    # Uncomment and configure the following if you need to push to Docker Hub
    # - name: Login to Docker Hub
    #   run: echo ${{ secrets.DOCKER_PASSWORD }} | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin
    # - name: Push Docker image
    #   run: docker tag keylogger-project:latest <your-dockerhub-username>/keylogger-project:latest
    #   run: docker push <your-dockerhub-username>/keylogger-project:latest

  deploy:
    runs-on: ubuntu-latest
    needs: dockerize

    steps:
    # Step 1: Deploy to Remote Server
    - name: Deploy to Remote Server
      uses: appleboy/ssh-action@v0.1.7
      with:
        host: ${{ secrets.SERVER_HOST }}
        username: ${{ secrets.SERVER_USER }}
        key: ${{ secrets.SERVER_KEY }}
        script: |
          docker stop Key-Logger-main || true
          docker rm Key-Logger-main || true
          docker run -d --name Key-Logger-main -p 80:80 Key-Logger-main

